version: "3"
name: drlt
services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - 5000:3000
    environment:
      - WDS_SOCKET_PORT=5000
    volumes:
      - ./:/app
      - /app/node_modules
